services:
  - type: web
    name: lumiere-json-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm exec json-server --watch db.json --port $PORT --host 0.0.0.0
    envVars:
      - key: NODE_VERSION
        value: 22
